name: Elixir CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MIX_ENV: test
  ELIXIR_VERSION: "1.14.2"
  ERLANG_VERSION: "25.1.2"

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check Formatting
        run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Run tests
        run: mix test

  hex-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check retired deps
        run: mix hex.audit

  unused-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check unused deps
        run: mix deps.unlock --check-unused

  deps-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check vulnerable dependencies
        run: mix deps.audit

  migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check migrations rollback
        run: |
          mix ecto.create
          mix ecto.migrate
          mix ecto.rollback --all

  credo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check credo
        run: mix credo --strict

  dialyzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check dialyzer
        run:
          - ls _build/${MIX_ENV}
          - mix dialyzer

  gradient:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check gradient
        run: mix gradient

  sobelow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.ERLANG_VERSION }}

      - name: Check sobelow
        run: mix sobelow --config
