name: Deploy on fly

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Generate short sha
        id: short-sha
        uses: actions/github-script@v6
        with:
          script: return "${{ github.sha }}".slice(0, 7)
          result-encoding: string

      - name: Set fly config
        id: set-fly-config
        run: |
          config=`flyctl config show`
          echo "::set-output name=fly-config::$config"

      - name: Publish image to registry
        run: flyctl deploy --image-label ${{ steps.short-sha.outputs.result }} --build-only --push

      - name: Update machines image
        run: flyctl image update --image registry.fly.io/${{ fromJson(steps.set-fly-config.outputs.fly-config)}}:${{ steps.short-sha.outputs.result }}
