name: Deploy on fly

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Generate short sha
        id: short-sha
        uses: actions/github-script@v6
        with:
          script: return "${{ github.sha }}".slice(0, 7)
          result-encoding: string

      - name: Set app name
        run: |
          app_name=`flyctl config show | jq -r '.app'`
          echo "FLY_APP_NAME=$app_name" >> $GITHUB_ENV

      - name: Build and push image
        run: flyctl deploy --image-label ${{ steps.short-sha.outputs.result }} --build-only --push

      - name: Update machines image
        run: flyctl image update --yes --image registry.fly.io/$FLY_APP_NAME:${{ steps.short-sha.outputs.result }}
