name: Elixir CI

on: pull_request

env:
  MIX_ENV: test

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["25.1.2"]
        elixir: ["1.14.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run tests
        run: mix test

      - name: Check retired deps
        run: mix hex.audit

      - name: Check unused deps
        run: mix deps.unlock --check-unused

      - name: Check vulnerable dependencies
        run: mix deps.audit

      - name: Check migrations rollback
        run: |
          mix ecto.create
          mix ecto.migrate
          mix ecto.rollback --all

      - name: Check credo
        run: mix credo --strict

      - name: Check dialyzer
        run: mix dialyzer

      - name: Check sobelow
        run: mix sobelow --config
